import { BotSettings, PositionRecord } from '../src/types.js'

/**
 * A complete, sane BotSettings object. Tests override only the few fields they
 * exercise via `makeSettings({ ... })`, keeping each test focused on one rule.
 */
export function makeSettings(overrides: Partial<BotSettings> = {}): BotSettings {
  const base: BotSettings = {
    watchlist: ['BTC', 'ETH'],
    pipeline_cron: '*/15 * * * *',
    default_horizon: 'auto',
    min_confidence: 0.6,
    max_position_size_usd: 1000,
    approval_required: false,
    stop_loss_atr: 2,
    take_profit_atr: 4,
    max_risk_per_trade: 0.02,
    max_open_positions: 5,
    cache_ttl_hours: 6,
    discover_cron: '0 */4 * * *',
    discover_min_score: 70,
    discover_top_n: 10,
    discover_auto_add: false,
    discover_min_volume_usd: 1_000_000,
    monitor_auto_run: true,
    monitor_model: 'a',
    monitor_cron: '*/30 * * * *',
    monitor_adjust_sltp: true,
    monitor_auto_approve: false,
    monitor_sl_pct_short: 3,
    monitor_sl_pct_medium: 6,
    monitor_sl_pct_long: 12,
    monitor_tp_pct_short: 6,
    monitor_tp_pct_medium: 12,
    monitor_tp_pct_long: 24,
    oco_sl_buffer_pct: 0.5,
    min_trade_usdc: 10,
    fee_rate: 0.001,
    monitor_trust_llm_sltp: false,
    monitor_use_horizon: true,
    monitor_history_tf: '1h',
    monitor_history_count: 24,
    monitor_min_confidence: 0.6,
    monitor_breakeven_pct: 1,
    monitor_adjust_cooldown_min: 30,
    utc_offset_hours: 0,
    llm_debug_fetch_limit: 200,
    llm_retain_days: 0,
    llm_allow_parallel_same_url: false,
    entry_timing_enabled: false,
    entry_pullback_pct: 1,
    entry_invalidate_pct: 3,
    entry_max_chase_pct: 1,
    entry_ttl_minutes: 30,
    entry_on_expiry: 'cancel',
    entry_poll_seconds: 5,
    llm_analyst_base_url: '',
    llm_analyst_model: '',
    llm_analyst_max_tokens: 0,
    llm_extractor_base_url: '',
    llm_extractor_model: '',
    llm_extractor_max_tokens: 0,
    llm_discoverer_base_url: '',
    llm_discoverer_model: '',
    llm_discoverer_max_tokens: 0,
    llm_discoverer_extractor_base_url: '',
    llm_discoverer_extractor_model: '',
    llm_discoverer_extractor_max_tokens: 0,
    llm_monitor_a_base_url: '',
    llm_monitor_a_model: '',
    llm_monitor_a_max_tokens: 0,
    llm_monitor_b_base_url: '',
    llm_monitor_b_model: '',
    llm_monitor_b_max_tokens: 0,
  }
  return { ...base, ...overrides }
}

export function makePosition(overrides: Partial<PositionRecord> = {}): PositionRecord {
  const base: PositionRecord = {
    id: 1,
    coin: 'BTC',
    side: 'BUY',
    quantity: 0.5,
    entry_price: 100,
    stop_loss: 95,
    take_profit: 110,
    current_sl: 95,
    status: 'OPEN',
    pnl: null,
    horizon: 'medium',
    oco_order_list_id: null,
    oco_sl_order_id: null,
    oco_tp_order_id: null,
    oco_status: 'NONE',
    oco_synced_at: null,
    created_at: '2026-06-13T00:00:00.000Z',
  }
  return { ...base, ...overrides }
}
